version: "3.9"
services:
  db:
    image: postgres:14
    container_name: ddd-todo-db
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "todo"
volumes:
  db-store:
